Get data from dataplane inventory secret
openstack-k8s-operators/swift-operator pull request #226
Opened 2024-06-05 14:30 UTC by fao89

2024-06-11 12:13 UTC, cschwede reviewed
With this patch applied, I see a panic in the operator:

```
2024-06-11T12:11:40.762Z	INFO	Observed a panic in reconciler: interface conversion: interface {} is []interface {}, not []string	{"controller": "swiftring", "controllerGroup": "swift.openstack.org", "controllerKind": "SwiftRing", "SwiftRing": {"name":"swift-ring","namespace":"openstack"}, "namespace": "openstack", "name": "swift-ring", "reconcileID": "778ce5b7-a06c-4d0d-ab35-53da8874af0d"}
panic: interface conversion: interface {} is []interface {}, not []string [recovered]
	panic: interface conversion: interface {} is []interface {}, not []string

goroutine 364 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:116 +0x1fa
panic({0x1a72120, 0xc000442c00})
	/usr/lib/golang/src/runtime/panic.go:884 +0x213
github.com/openstack-k8s-operators/swift-operator/pkg/swiftring.DeviceList({0x1f6afc0, 0xc006ff06c0}, 0xc0006444d0, 0x8?)
	/remote-source/pkg/swiftring/funcs.go:110 +0xe6b
```

I'm looking into a possible fix.

2024-06-11 12:19 UTC, fao89 commented
The failure seems to be here:
```
nodeSetGroup.Vars[DataplaneDisks].([]byte)
```
where we try to cast the DataplaneDisks variable

2024-06-11 15:25 UTC, cschwede requested changes
This worked in my tests with one minor change, please see my inline comment

2024-06-11 15:25 UTC, cschwede commented on pkg/swiftring/funcs.go
> +		if slices.Contains(nodeSetGroup.Vars["edpm_services"].([]string), "swift") {
I had to change `[]string` to `[]interface {}` to make this work:

`if slices.Contains(nodeSetGroup.Vars["edpm_services"].([]interface {}), "swift") {
`

2024-06-11 18:12 UTC, fao89 commented
/test swift-operator-build-deploy-kuttl

2024-06-11 20:44 UTC, fao89 commented
/test swift-operator-build-deploy-kuttl

2024-06-12 06:53 UTC, cschwede approved these changes
/lgtm

Tested, works fine for me - thx a lot for your help on this!

2024-06-12 06:53 UTC, cschwede commented
/test swift-operator-build-deploy-kuttl

2024-06-12 08:12 UTC, merged